// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Certifac.Models
{
    public partial class Cer_AddendasContext : DbContext
    {
        public Cer_AddendasContext()
        {
        }

        public Cer_AddendasContext(DbContextOptions<Cer_AddendasContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Addenda> Addendas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Modern_Spanish_CI_AS");

            modelBuilder.Entity<Addenda>(entity =>
            {
                entity.HasKey(e => e.IdAddenda);

                entity.Property(e => e.IdAddenda).ValueGeneratedNever();

                entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.NombreAddenda).HasMaxLength(50);

                entity.Property(e => e.Usuario)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Xml).HasColumnName("XML");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}